/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { ButtonProps, FlexProps, IconProps, ImageProps, TextFieldProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type CajaOverridesProps = {
    Caja?: PrimitiveOverrideProps<ViewProps>;
    "BG Sistema"?: PrimitiveOverrideProps<FlexProps>;
    "BG System"?: PrimitiveOverrideProps<ViewProps>;
    Menu3218?: PrimitiveOverrideProps<FlexProps>;
    Menu3219?: PrimitiveOverrideProps<ImageProps>;
    Menu3231?: PrimitiveOverrideProps<ViewProps>;
    Mantenimiento3232?: PrimitiveOverrideProps<FlexProps>;
    Mantenimiento3243?: PrimitiveOverrideProps<TextProps>;
    "caret-down3247"?: PrimitiveOverrideProps<ViewProps>;
    Vector3264?: PrimitiveOverrideProps<IconProps>;
    Usuarios3265?: PrimitiveOverrideProps<FlexProps>;
    Usuarios3272?: PrimitiveOverrideProps<TextProps>;
    "caret-down3273"?: PrimitiveOverrideProps<ViewProps>;
    Vector3300?: PrimitiveOverrideProps<IconProps>;
    Agencias?: PrimitiveOverrideProps<FlexProps>;
    Agencia?: PrimitiveOverrideProps<TextProps>;
    "caret-down3306"?: PrimitiveOverrideProps<ViewProps>;
    Vector3307?: PrimitiveOverrideProps<IconProps>;
    Reportes3308?: PrimitiveOverrideProps<FlexProps>;
    Reportes3309?: PrimitiveOverrideProps<TextProps>;
    "caret-down3311"?: PrimitiveOverrideProps<ViewProps>;
    Vector3315?: PrimitiveOverrideProps<IconProps>;
    Logout3316?: PrimitiveOverrideProps<FlexProps>;
    Logout3317?: PrimitiveOverrideProps<TextProps>;
    logo?: PrimitiveOverrideProps<ImageProps>;
    "Linea Sistema"?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 13321"?: PrimitiveOverrideProps<ViewProps>;
    Footer?: PrimitiveOverrideProps<FlexProps>;
    "Copyright (c) 2012 - 2013 CCM. All rights reserved"?: PrimitiveOverrideProps<TextProps>;
    footer?: PrimitiveOverrideProps<ImageProps>;
    Input3325?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13326"?: PrimitiveOverrideProps<ViewProps>;
    "Deposito disponible"?: PrimitiveOverrideProps<TextProps>;
    "$9999.993329"?: PrimitiveOverrideProps<TextProps>;
    "Line 4"?: PrimitiveOverrideProps<IconProps>;
    "Line 5"?: PrimitiveOverrideProps<IconProps>;
    "+"?: PrimitiveOverrideProps<TextProps>;
    "Text Button6214025"?: PrimitiveOverrideProps<ButtonProps>;
    "BTN Buscar3333"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13334"?: PrimitiveOverrideProps<ViewProps>;
    Filtrar?: PrimitiveOverrideProps<TextProps>;
    "BTN Buscar3341"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13342"?: PrimitiveOverrideProps<ViewProps>;
    Agregar?: PrimitiveOverrideProps<TextProps>;
    "BTN Buscar3344"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13345"?: PrimitiveOverrideProps<ViewProps>;
    Pagar?: PrimitiveOverrideProps<TextProps>;
    "BTN Buscar3347"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13348"?: PrimitiveOverrideProps<ViewProps>;
    Cancelar?: PrimitiveOverrideProps<TextProps>;
    Caja3353?: PrimitiveOverrideProps<TextProps>;
    Input3354?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13355"?: PrimitiveOverrideProps<ViewProps>;
    Input3356?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13358"?: PrimitiveOverrideProps<ViewProps>;
    Input3359?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13363"?: PrimitiveOverrideProps<ViewProps>;
    Input3364?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13365"?: PrimitiveOverrideProps<ViewProps>;
    Select3366?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13367"?: PrimitiveOverrideProps<ViewProps>;
    "chevron-down3368"?: PrimitiveOverrideProps<ViewProps>;
    Vector3369?: PrimitiveOverrideProps<IconProps>;
    "Tipo de servicio"?: PrimitiveOverrideProps<TextProps>;
    Select3371?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13372"?: PrimitiveOverrideProps<ViewProps>;
    "chevron-down3373"?: PrimitiveOverrideProps<ViewProps>;
    Vector3374?: PrimitiveOverrideProps<IconProps>;
    Seleccione3375?: PrimitiveOverrideProps<TextProps>;
    Select3376?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13377"?: PrimitiveOverrideProps<ViewProps>;
    "#Cheque / Tarjeta3378"?: PrimitiveOverrideProps<TextProps>;
    Select3379?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13380"?: PrimitiveOverrideProps<ViewProps>;
    "chevron-down3381"?: PrimitiveOverrideProps<ViewProps>;
    Vector3382?: PrimitiveOverrideProps<IconProps>;
    Seleccione3384?: PrimitiveOverrideProps<TextProps>;
    Select3386?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13387"?: PrimitiveOverrideProps<ViewProps>;
    "#Cheque / Tarjeta3393"?: PrimitiveOverrideProps<TextProps>;
    ID3394?: PrimitiveOverrideProps<TextProps>;
    Pagos?: PrimitiveOverrideProps<TextProps>;
    "FORMAS DE PAGO"?: PrimitiveOverrideProps<TextProps>;
    Nombre3397?: PrimitiveOverrideProps<TextProps>;
    "Direcci\u00F3n3398"?: PrimitiveOverrideProps<TextProps>;
    Saldo3402?: PrimitiveOverrideProps<TextProps>;
    "MONTO a Pagar3414"?: PrimitiveOverrideProps<TextProps>;
    ID3415?: PrimitiveOverrideProps<TextProps>;
    Nombre3416?: PrimitiveOverrideProps<TextProps>;
    "Direcci\u00F3n3417"?: PrimitiveOverrideProps<TextProps>;
    Saldo3418?: PrimitiveOverrideProps<TextProps>;
    "Sub TOTAL"?: PrimitiveOverrideProps<TextProps>;
    "$9999.993420"?: PrimitiveOverrideProps<TextProps>;
    "Total Pagado"?: PrimitiveOverrideProps<TextProps>;
    "Diferencia Trabajo"?: PrimitiveOverrideProps<TextProps>;
    "$9999.993428"?: PrimitiveOverrideProps<TextProps>;
    "$9999.993429"?: PrimitiveOverrideProps<TextProps>;
    "MONTO a Pagar3430"?: PrimitiveOverrideProps<TextProps>;
    "C & W"?: PrimitiveOverrideProps<TextProps>;
    CLARO?: PrimitiveOverrideProps<TextProps>;
    DIGICEL?: PrimitiveOverrideProps<TextProps>;
    TIGO?: PrimitiveOverrideProps<TextProps>;
    ENSA?: PrimitiveOverrideProps<TextProps>;
    NATURGY?: PrimitiveOverrideProps<TextProps>;
    IDAAN?: PrimitiveOverrideProps<TextProps>;
    "METRO BUS"?: PrimitiveOverrideProps<TextProps>;
    "Text Button641104"?: PrimitiveOverrideProps<ButtonProps>;
    TextField?: PrimitiveOverrideProps<TextFieldProps>;
    Button?: PrimitiveOverrideProps<ButtonProps>;
} & EscapeHatchProps;
export declare type CajaProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: CajaOverridesProps | undefined | null;
}>;
export default function Caja(props: CajaProps): React.ReactElement;
