/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type CajasAgenteOverridesProps = {
    CajasAgente?: PrimitiveOverrideProps<ViewProps>;
    "BG Sistema"?: PrimitiveOverrideProps<FlexProps>;
    Menu31632?: PrimitiveOverrideProps<FlexProps>;
    Menu31639?: PrimitiveOverrideProps<ImageProps>;
    Menu31640?: PrimitiveOverrideProps<ViewProps>;
    Mantenimiento31641?: PrimitiveOverrideProps<FlexProps>;
    Mantenimiento31642?: PrimitiveOverrideProps<TextProps>;
    "caret-down31643"?: PrimitiveOverrideProps<ViewProps>;
    Vector31644?: PrimitiveOverrideProps<IconProps>;
    Usuarios31645?: PrimitiveOverrideProps<FlexProps>;
    Usuarios31646?: PrimitiveOverrideProps<TextProps>;
    "caret-down31647"?: PrimitiveOverrideProps<ViewProps>;
    Vector31648?: PrimitiveOverrideProps<IconProps>;
    Agencias?: PrimitiveOverrideProps<FlexProps>;
    Agencia?: PrimitiveOverrideProps<TextProps>;
    "caret-down31651"?: PrimitiveOverrideProps<ViewProps>;
    Vector31652?: PrimitiveOverrideProps<IconProps>;
    Reportes31653?: PrimitiveOverrideProps<FlexProps>;
    Reportes31688?: PrimitiveOverrideProps<TextProps>;
    "caret-down31715"?: PrimitiveOverrideProps<ViewProps>;
    Vector31716?: PrimitiveOverrideProps<IconProps>;
    Logout31720?: PrimitiveOverrideProps<FlexProps>;
    Logout31721?: PrimitiveOverrideProps<TextProps>;
    Logo?: PrimitiveOverrideProps<FlexProps>;
    logo?: PrimitiveOverrideProps<ImageProps>;
    "Linea Sistema"?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 131729"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 32"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 33"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 34"?: PrimitiveOverrideProps<ViewProps>;
    "Line 6"?: PrimitiveOverrideProps<IconProps>;
    Footer?: PrimitiveOverrideProps<FlexProps>;
    "Copyright (c) 2012 - 2013 CCM. All rights reserved"?: PrimitiveOverrideProps<TextProps>;
    footer?: PrimitiveOverrideProps<ImageProps>;
    "De:"?: PrimitiveOverrideProps<TextProps>;
    "Hasta:"?: PrimitiveOverrideProps<TextProps>;
    Select31749?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131750"?: PrimitiveOverrideProps<ViewProps>;
    "Fecha inicio"?: PrimitiveOverrideProps<TextProps>;
    Select31752?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131753"?: PrimitiveOverrideProps<ViewProps>;
    "Fecha final"?: PrimitiveOverrideProps<TextProps>;
    "+"?: PrimitiveOverrideProps<TextProps>;
    "BTN Buscar31756"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131757"?: PrimitiveOverrideProps<ViewProps>;
    Actualizar?: PrimitiveOverrideProps<TextProps>;
    "BTN Buscar31761"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131762"?: PrimitiveOverrideProps<ViewProps>;
    Filtrar?: PrimitiveOverrideProps<TextProps>;
    "Caja - %Agente%"?: PrimitiveOverrideProps<TextProps>;
    Select31765?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131766"?: PrimitiveOverrideProps<ViewProps>;
    "chevron-down"?: PrimitiveOverrideProps<ViewProps>;
    Vector31768?: PrimitiveOverrideProps<IconProps>;
    Seleccione?: PrimitiveOverrideProps<TextProps>;
    Select31770?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131771"?: PrimitiveOverrideProps<ViewProps>;
    "Monto Depositado"?: PrimitiveOverrideProps<TextProps>;
    Select31773?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131775"?: PrimitiveOverrideProps<ViewProps>;
    "Min\u00EDmo en Dep\u00F3sito"?: PrimitiveOverrideProps<TextProps>;
    Cuenta31779?: PrimitiveOverrideProps<TextProps>;
    "Lista de Dep\u00F3sitos"?: PrimitiveOverrideProps<TextProps>;
    Monto?: PrimitiveOverrideProps<TextProps>;
    Comprobante?: PrimitiveOverrideProps<TextProps>;
    "Min\u00EDmo Dep\u00F3sito"?: PrimitiveOverrideProps<TextProps>;
    ID?: PrimitiveOverrideProps<TextProps>;
    Fecha?: PrimitiveOverrideProps<TextProps>;
    Hora?: PrimitiveOverrideProps<TextProps>;
    Cuenta31801?: PrimitiveOverrideProps<TextProps>;
    "Dep\u00F3sito"?: PrimitiveOverrideProps<TextProps>;
    "Confirmaci\u00F3n"?: PrimitiveOverrideProps<TextProps>;
    "Confirmado por:"?: PrimitiveOverrideProps<TextProps>;
    "checkmark-circle-outline31805"?: PrimitiveOverrideProps<ViewProps>;
    Vector31806?: PrimitiveOverrideProps<IconProps>;
    Vector31807?: PrimitiveOverrideProps<IconProps>;
    "checkmark-circle-outline31808"?: PrimitiveOverrideProps<ViewProps>;
    Vector31809?: PrimitiveOverrideProps<IconProps>;
    Vector31810?: PrimitiveOverrideProps<IconProps>;
    attach?: PrimitiveOverrideProps<ViewProps>;
    Vector31812?: PrimitiveOverrideProps<IconProps>;
    "checkmark-circle-outline31813"?: PrimitiveOverrideProps<ViewProps>;
    Vector31814?: PrimitiveOverrideProps<IconProps>;
    Vector31815?: PrimitiveOverrideProps<IconProps>;
} & EscapeHatchProps;
export declare type CajasAgenteProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: CajasAgenteOverridesProps | undefined | null;
}>;
export default function CajasAgente(props: CajasAgenteProps): React.ReactElement;
