/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type ComprobantedePagoOverridesProps = {
    "1"?: PrimitiveOverrideProps<TextProps>;
    "2"?: PrimitiveOverrideProps<TextProps>;
    "3"?: PrimitiveOverrideProps<TextProps>;
    "4"?: PrimitiveOverrideProps<TextProps>;
    "5"?: PrimitiveOverrideProps<TextProps>;
    ComprobantedePago?: PrimitiveOverrideProps<ViewProps>;
    "BG Sistema"?: PrimitiveOverrideProps<FlexProps>;
    "BG System"?: PrimitiveOverrideProps<ViewProps>;
    Menu3524?: PrimitiveOverrideProps<FlexProps>;
    Menu3525?: PrimitiveOverrideProps<ImageProps>;
    Menu3526?: PrimitiveOverrideProps<ViewProps>;
    Mantenimiento3527?: PrimitiveOverrideProps<FlexProps>;
    Mantenimiento3528?: PrimitiveOverrideProps<TextProps>;
    "caret-down3529"?: PrimitiveOverrideProps<ViewProps>;
    Vector3530?: PrimitiveOverrideProps<IconProps>;
    Usuarios3537?: PrimitiveOverrideProps<FlexProps>;
    Usuarios3538?: PrimitiveOverrideProps<TextProps>;
    "caret-down3539"?: PrimitiveOverrideProps<ViewProps>;
    Vector3541?: PrimitiveOverrideProps<IconProps>;
    Agencias?: PrimitiveOverrideProps<FlexProps>;
    Agencia?: PrimitiveOverrideProps<TextProps>;
    "caret-down3544"?: PrimitiveOverrideProps<ViewProps>;
    Vector3545?: PrimitiveOverrideProps<IconProps>;
    Reportes3546?: PrimitiveOverrideProps<FlexProps>;
    Reportes3547?: PrimitiveOverrideProps<TextProps>;
    "caret-down3548"?: PrimitiveOverrideProps<ViewProps>;
    Vector3549?: PrimitiveOverrideProps<IconProps>;
    Logout3550?: PrimitiveOverrideProps<FlexProps>;
    Logout3551?: PrimitiveOverrideProps<TextProps>;
    logo?: PrimitiveOverrideProps<ImageProps>;
    Footer?: PrimitiveOverrideProps<FlexProps>;
    "Copyright (c) 2012 - 2013 CCM. All rights reserved"?: PrimitiveOverrideProps<TextProps>;
    footer?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 15"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 16"?: PrimitiveOverrideProps<ViewProps>;
    "De:"?: PrimitiveOverrideProps<TextProps>;
    "Line 5"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 20"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 21"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 22"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 23"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 24"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 25"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 26"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 27"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 28"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 29"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 30"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 31"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 32"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 33"?: PrimitiveOverrideProps<ViewProps>;
    "BTN Buscar3580"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13582"?: PrimitiveOverrideProps<ViewProps>;
    Filtrar?: PrimitiveOverrideProps<TextProps>;
    "BTN Buscar3584"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13585"?: PrimitiveOverrideProps<ViewProps>;
    Buscar?: PrimitiveOverrideProps<TextProps>;
    "Comprobante de Pago"?: PrimitiveOverrideProps<TextProps>;
    "A:"?: PrimitiveOverrideProps<TextProps>;
    Select3589?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13590"?: PrimitiveOverrideProps<ViewProps>;
    "chevron-down3591"?: PrimitiveOverrideProps<ViewProps>;
    Vector3592?: PrimitiveOverrideProps<IconProps>;
    EMPRESA?: PrimitiveOverrideProps<TextProps>;
    Select3594?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13595"?: PrimitiveOverrideProps<ViewProps>;
    "chevron-down3596"?: PrimitiveOverrideProps<ViewProps>;
    Vector3601?: PrimitiveOverrideProps<IconProps>;
    "SUCURSAL / AGENTE"?: PrimitiveOverrideProps<TextProps>;
    ID?: PrimitiveOverrideProps<TextProps>;
    Cliente3604?: PrimitiveOverrideProps<TextProps>;
    Servicio?: PrimitiveOverrideProps<TextProps>;
    Empresa?: PrimitiveOverrideProps<TextProps>;
    Select3607?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13608"?: PrimitiveOverrideProps<ViewProps>;
    "Fecha inicio"?: PrimitiveOverrideProps<TextProps>;
    Select3610?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13611"?: PrimitiveOverrideProps<ViewProps>;
    "Fecha fin"?: PrimitiveOverrideProps<TextProps>;
    Select3613?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13614"?: PrimitiveOverrideProps<ViewProps>;
    Cliente3615?: PrimitiveOverrideProps<TextProps>;
    "refresh-circle-outline3616"?: PrimitiveOverrideProps<ViewProps>;
    Vector3617?: PrimitiveOverrideProps<IconProps>;
    Vector3618?: PrimitiveOverrideProps<IconProps>;
    Vector3619?: PrimitiveOverrideProps<IconProps>;
    "refresh-circle-outline3620"?: PrimitiveOverrideProps<ViewProps>;
    Vector3631?: PrimitiveOverrideProps<IconProps>;
    Vector3641?: PrimitiveOverrideProps<IconProps>;
    Vector3642?: PrimitiveOverrideProps<IconProps>;
    "refresh-circle-outline3643"?: PrimitiveOverrideProps<ViewProps>;
    Vector3684?: PrimitiveOverrideProps<IconProps>;
    Vector3685?: PrimitiveOverrideProps<IconProps>;
    Vector3686?: PrimitiveOverrideProps<IconProps>;
    "refresh-circle-outline3688"?: PrimitiveOverrideProps<ViewProps>;
    Vector3689?: PrimitiveOverrideProps<IconProps>;
    Vector3690?: PrimitiveOverrideProps<IconProps>;
    Vector3696?: PrimitiveOverrideProps<IconProps>;
    "refresh-circle-outline3697"?: PrimitiveOverrideProps<ViewProps>;
    Vector3698?: PrimitiveOverrideProps<IconProps>;
    Vector3699?: PrimitiveOverrideProps<IconProps>;
    Vector3700?: PrimitiveOverrideProps<IconProps>;
    Print3701?: PrimitiveOverrideProps<ViewProps>;
    "print-outline3702"?: PrimitiveOverrideProps<ViewProps>;
    Vector3703?: PrimitiveOverrideProps<IconProps>;
    Vector3704?: PrimitiveOverrideProps<IconProps>;
    Vector3705?: PrimitiveOverrideProps<IconProps>;
    Vector3706?: PrimitiveOverrideProps<IconProps>;
    Print3707?: PrimitiveOverrideProps<ViewProps>;
    "print-outline3713"?: PrimitiveOverrideProps<ViewProps>;
    Vector3714?: PrimitiveOverrideProps<IconProps>;
    Vector3715?: PrimitiveOverrideProps<IconProps>;
    Vector3733?: PrimitiveOverrideProps<IconProps>;
    Vector3734?: PrimitiveOverrideProps<IconProps>;
    Print3735?: PrimitiveOverrideProps<ViewProps>;
    "print-outline3744"?: PrimitiveOverrideProps<ViewProps>;
    Vector3745?: PrimitiveOverrideProps<IconProps>;
    Vector3746?: PrimitiveOverrideProps<IconProps>;
    Vector3747?: PrimitiveOverrideProps<IconProps>;
    Vector3779?: PrimitiveOverrideProps<IconProps>;
    Print3780?: PrimitiveOverrideProps<ViewProps>;
    "print-outline3781"?: PrimitiveOverrideProps<ViewProps>;
    Vector3782?: PrimitiveOverrideProps<IconProps>;
    Vector3783?: PrimitiveOverrideProps<IconProps>;
    Vector3784?: PrimitiveOverrideProps<IconProps>;
    Vector3786?: PrimitiveOverrideProps<IconProps>;
    Print3787?: PrimitiveOverrideProps<ViewProps>;
    "print-outline3788"?: PrimitiveOverrideProps<ViewProps>;
    Vector3789?: PrimitiveOverrideProps<IconProps>;
    Vector3790?: PrimitiveOverrideProps<IconProps>;
    Vector3791?: PrimitiveOverrideProps<IconProps>;
    Vector3795?: PrimitiveOverrideProps<IconProps>;
    "refresh-circle-outline3796"?: PrimitiveOverrideProps<ViewProps>;
    Vector3797?: PrimitiveOverrideProps<IconProps>;
    Vector3798?: PrimitiveOverrideProps<IconProps>;
    Vector3799?: PrimitiveOverrideProps<IconProps>;
    "refresh-circle-outline3800"?: PrimitiveOverrideProps<ViewProps>;
    Vector3802?: PrimitiveOverrideProps<IconProps>;
    Vector3803?: PrimitiveOverrideProps<IconProps>;
    Vector3804?: PrimitiveOverrideProps<IconProps>;
    "refresh-circle-outline3805"?: PrimitiveOverrideProps<ViewProps>;
    Vector3806?: PrimitiveOverrideProps<IconProps>;
    Vector3807?: PrimitiveOverrideProps<IconProps>;
    Vector3808?: PrimitiveOverrideProps<IconProps>;
    "refresh-circle-outline3809"?: PrimitiveOverrideProps<ViewProps>;
    Vector3810?: PrimitiveOverrideProps<IconProps>;
    Vector3811?: PrimitiveOverrideProps<IconProps>;
    Vector3812?: PrimitiveOverrideProps<IconProps>;
    "refresh-circle-outline3813"?: PrimitiveOverrideProps<ViewProps>;
    Vector3814?: PrimitiveOverrideProps<IconProps>;
    Vector3823?: PrimitiveOverrideProps<IconProps>;
    Vector3824?: PrimitiveOverrideProps<IconProps>;
    Print3825?: PrimitiveOverrideProps<ViewProps>;
    "print-outline3826"?: PrimitiveOverrideProps<ViewProps>;
    Vector3827?: PrimitiveOverrideProps<IconProps>;
    Vector3833?: PrimitiveOverrideProps<IconProps>;
    Vector3834?: PrimitiveOverrideProps<IconProps>;
    Vector3835?: PrimitiveOverrideProps<IconProps>;
    Print3838?: PrimitiveOverrideProps<ViewProps>;
    "print-outline3839"?: PrimitiveOverrideProps<ViewProps>;
    Vector3840?: PrimitiveOverrideProps<IconProps>;
    Vector3841?: PrimitiveOverrideProps<IconProps>;
    Vector3842?: PrimitiveOverrideProps<IconProps>;
    Vector3843?: PrimitiveOverrideProps<IconProps>;
    Print3844?: PrimitiveOverrideProps<ViewProps>;
    "print-outline3845"?: PrimitiveOverrideProps<ViewProps>;
    Vector3846?: PrimitiveOverrideProps<IconProps>;
    Vector3847?: PrimitiveOverrideProps<IconProps>;
    Vector3848?: PrimitiveOverrideProps<IconProps>;
    Vector3849?: PrimitiveOverrideProps<IconProps>;
    Print3850?: PrimitiveOverrideProps<ViewProps>;
    "print-outline3851"?: PrimitiveOverrideProps<ViewProps>;
    Vector3852?: PrimitiveOverrideProps<IconProps>;
    Vector3853?: PrimitiveOverrideProps<IconProps>;
    Vector3854?: PrimitiveOverrideProps<IconProps>;
    Vector3855?: PrimitiveOverrideProps<IconProps>;
    Print3856?: PrimitiveOverrideProps<ViewProps>;
    "print-outline3858"?: PrimitiveOverrideProps<ViewProps>;
    Vector3859?: PrimitiveOverrideProps<IconProps>;
    Vector3860?: PrimitiveOverrideProps<IconProps>;
    Vector3866?: PrimitiveOverrideProps<IconProps>;
    Vector3867?: PrimitiveOverrideProps<IconProps>;
    "refresh-circle-outline3868"?: PrimitiveOverrideProps<ViewProps>;
    Vector3875?: PrimitiveOverrideProps<IconProps>;
    Vector3876?: PrimitiveOverrideProps<IconProps>;
    Vector3877?: PrimitiveOverrideProps<IconProps>;
    "refresh-circle-outline3878"?: PrimitiveOverrideProps<ViewProps>;
    Vector3879?: PrimitiveOverrideProps<IconProps>;
    Vector3880?: PrimitiveOverrideProps<IconProps>;
    Vector3881?: PrimitiveOverrideProps<IconProps>;
    "refresh-circle-outline3882"?: PrimitiveOverrideProps<ViewProps>;
    Vector3883?: PrimitiveOverrideProps<IconProps>;
    Vector3884?: PrimitiveOverrideProps<IconProps>;
    Vector3885?: PrimitiveOverrideProps<IconProps>;
    "refresh-circle-outline3886"?: PrimitiveOverrideProps<ViewProps>;
    Vector3897?: PrimitiveOverrideProps<IconProps>;
    Vector3904?: PrimitiveOverrideProps<IconProps>;
    Vector3905?: PrimitiveOverrideProps<IconProps>;
    "refresh-circle-outline3906"?: PrimitiveOverrideProps<ViewProps>;
    Vector3907?: PrimitiveOverrideProps<IconProps>;
    Vector3908?: PrimitiveOverrideProps<IconProps>;
    Vector3909?: PrimitiveOverrideProps<IconProps>;
    Print3910?: PrimitiveOverrideProps<ViewProps>;
    "print-outline3911"?: PrimitiveOverrideProps<ViewProps>;
    Vector3912?: PrimitiveOverrideProps<IconProps>;
    Vector3919?: PrimitiveOverrideProps<IconProps>;
    Vector3920?: PrimitiveOverrideProps<IconProps>;
    Vector3950?: PrimitiveOverrideProps<IconProps>;
    Print3951?: PrimitiveOverrideProps<ViewProps>;
    "print-outline3952"?: PrimitiveOverrideProps<ViewProps>;
    Vector3953?: PrimitiveOverrideProps<IconProps>;
    Vector3967?: PrimitiveOverrideProps<IconProps>;
    Vector3972?: PrimitiveOverrideProps<IconProps>;
    Vector3973?: PrimitiveOverrideProps<IconProps>;
    Print3974?: PrimitiveOverrideProps<ViewProps>;
    "print-outline3975"?: PrimitiveOverrideProps<ViewProps>;
    Vector3976?: PrimitiveOverrideProps<IconProps>;
    Vector3977?: PrimitiveOverrideProps<IconProps>;
    Vector3978?: PrimitiveOverrideProps<IconProps>;
    Vector3979?: PrimitiveOverrideProps<IconProps>;
    Print3980?: PrimitiveOverrideProps<ViewProps>;
    "print-outline3981"?: PrimitiveOverrideProps<ViewProps>;
    Vector3982?: PrimitiveOverrideProps<IconProps>;
    Vector3983?: PrimitiveOverrideProps<IconProps>;
    Vector3989?: PrimitiveOverrideProps<IconProps>;
    Vector3990?: PrimitiveOverrideProps<IconProps>;
    Print3991?: PrimitiveOverrideProps<ViewProps>;
    "print-outline3992"?: PrimitiveOverrideProps<ViewProps>;
    Vector3993?: PrimitiveOverrideProps<IconProps>;
    Vector3994?: PrimitiveOverrideProps<IconProps>;
    Vector3995?: PrimitiveOverrideProps<IconProps>;
    Vector3996?: PrimitiveOverrideProps<IconProps>;
    "refresh-circle-outline31003"?: PrimitiveOverrideProps<ViewProps>;
    Vector31004?: PrimitiveOverrideProps<IconProps>;
    Vector31025?: PrimitiveOverrideProps<IconProps>;
    Vector31026?: PrimitiveOverrideProps<IconProps>;
    "refresh-circle-outline31053"?: PrimitiveOverrideProps<ViewProps>;
    Vector31054?: PrimitiveOverrideProps<IconProps>;
    Vector31055?: PrimitiveOverrideProps<IconProps>;
    Vector31056?: PrimitiveOverrideProps<IconProps>;
    Print31057?: PrimitiveOverrideProps<ViewProps>;
    "print-outline31058"?: PrimitiveOverrideProps<ViewProps>;
    Vector31068?: PrimitiveOverrideProps<IconProps>;
    Vector31069?: PrimitiveOverrideProps<IconProps>;
    Vector31070?: PrimitiveOverrideProps<IconProps>;
    Vector31071?: PrimitiveOverrideProps<IconProps>;
    Print31072?: PrimitiveOverrideProps<ViewProps>;
    "print-outline31073"?: PrimitiveOverrideProps<ViewProps>;
    Vector31074?: PrimitiveOverrideProps<IconProps>;
    Vector31075?: PrimitiveOverrideProps<IconProps>;
    Vector31076?: PrimitiveOverrideProps<IconProps>;
    Vector31077?: PrimitiveOverrideProps<IconProps>;
    "Group 4"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 56"?: PrimitiveOverrideProps<ViewProps>;
    CCM?: PrimitiveOverrideProps<TextProps>;
    "Agente Autorizado"?: PrimitiveOverrideProps<TextProps>;
    "RUC: Tel\u00E9fono: Correo: DOCUMENTO NO FISCAL RECIBO DE PAGO - TIGO APLICAR PAGO A 999999999 Fecha: dd/mm/aaaa 99:99 a.m."?: PrimitiveOverrideProps<TextProps>;
    "Cajero: C\u00F3digo de Operaci\u00F3n: 9999999 Monto de Operaci\u00F3n: 999999999 Monto Pagado: $9999.99 Cliente: # Cuenta: 999999999999 NO FISCAL"?: PrimitiveOverrideProps<TextProps>;
    Input?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131086"?: PrimitiveOverrideProps<ViewProps>;
    "Raz\u00F3n de Anulaci\u00F3n"?: PrimitiveOverrideProps<TextProps>;
    "BTN Agregar31088"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131089"?: PrimitiveOverrideProps<ViewProps>;
    Imprimir?: PrimitiveOverrideProps<TextProps>;
    "BTN Agregar31091"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131092"?: PrimitiveOverrideProps<ViewProps>;
    Anular?: PrimitiveOverrideProps<TextProps>;
    "BTN Agregar31094"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131095"?: PrimitiveOverrideProps<ViewProps>;
    "Adjuntar Recibo de Pago"?: PrimitiveOverrideProps<TextProps>;
    "BTN Numero31097"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131098"?: PrimitiveOverrideProps<ViewProps>;
    "BTN Numero31100"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131101"?: PrimitiveOverrideProps<ViewProps>;
    "BTN Numero31103"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131113"?: PrimitiveOverrideProps<ViewProps>;
    "BTN Numero31150"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131151"?: PrimitiveOverrideProps<ViewProps>;
    "BTN Numero31153"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131154"?: PrimitiveOverrideProps<ViewProps>;
    "BTN Siguiente"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131157"?: PrimitiveOverrideProps<ViewProps>;
    Siguiente?: PrimitiveOverrideProps<TextProps>;
    "BTN Ultimo"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131161"?: PrimitiveOverrideProps<ViewProps>;
    "\u00DAltimo"?: PrimitiveOverrideProps<TextProps>;
    "..."?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type ComprobantedePagoProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: ComprobantedePagoOverridesProps | undefined | null;
}>;
export default function ComprobantedePago(props: ComprobantedePagoProps): React.ReactElement;
