/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type DepositosOverridesProps = {
    Depositos?: PrimitiveOverrideProps<ViewProps>;
    "BG Sistema"?: PrimitiveOverrideProps<FlexProps>;
    "BG System"?: PrimitiveOverrideProps<ViewProps>;
    Menu31825?: PrimitiveOverrideProps<FlexProps>;
    Menu31826?: PrimitiveOverrideProps<ImageProps>;
    Menu31827?: PrimitiveOverrideProps<ViewProps>;
    Mantenimiento31828?: PrimitiveOverrideProps<FlexProps>;
    Mantenimiento31829?: PrimitiveOverrideProps<TextProps>;
    "caret-down31830"?: PrimitiveOverrideProps<ViewProps>;
    Vector31831?: PrimitiveOverrideProps<IconProps>;
    Usuarios31832?: PrimitiveOverrideProps<FlexProps>;
    Usuarios31833?: PrimitiveOverrideProps<TextProps>;
    "caret-down31834"?: PrimitiveOverrideProps<ViewProps>;
    Vector31835?: PrimitiveOverrideProps<IconProps>;
    Agencias?: PrimitiveOverrideProps<FlexProps>;
    Agencia?: PrimitiveOverrideProps<TextProps>;
    "caret-down31838"?: PrimitiveOverrideProps<ViewProps>;
    Vector31839?: PrimitiveOverrideProps<IconProps>;
    Reportes31840?: PrimitiveOverrideProps<FlexProps>;
    Reportes31841?: PrimitiveOverrideProps<TextProps>;
    "caret-down31842"?: PrimitiveOverrideProps<ViewProps>;
    Vector31843?: PrimitiveOverrideProps<IconProps>;
    Logout31844?: PrimitiveOverrideProps<FlexProps>;
    Logout31845?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 24"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 25"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 26"?: PrimitiveOverrideProps<ViewProps>;
    "Line 5"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 43"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 44"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 45"?: PrimitiveOverrideProps<ViewProps>;
    "Line 6"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 46"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 47"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 48"?: PrimitiveOverrideProps<ViewProps>;
    "Line 7"?: PrimitiveOverrideProps<IconProps>;
    "Linea Sistema"?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 131863"?: PrimitiveOverrideProps<ViewProps>;
    logo?: PrimitiveOverrideProps<ImageProps>;
    Footer?: PrimitiveOverrideProps<FlexProps>;
    "Copyright (c) 2012 - 2013 CCM. All rights reserved"?: PrimitiveOverrideProps<TextProps>;
    footer?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 37"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 38"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 39"?: PrimitiveOverrideProps<ViewProps>;
    ID31871?: PrimitiveOverrideProps<TextProps>;
    Fecha31872?: PrimitiveOverrideProps<TextProps>;
    Hora31873?: PrimitiveOverrideProps<TextProps>;
    Cuenta31874?: PrimitiveOverrideProps<TextProps>;
    "Dep\u00F3sito31875"?: PrimitiveOverrideProps<TextProps>;
    "Confirmaci\u00F3n31876"?: PrimitiveOverrideProps<TextProps>;
    "Ver Comprobante31877"?: PrimitiveOverrideProps<TextProps>;
    "Ver Comprobante31878"?: PrimitiveOverrideProps<TextProps>;
    "Ver Comprobante31879"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 40"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 41"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 42"?: PrimitiveOverrideProps<ViewProps>;
    ID31883?: PrimitiveOverrideProps<TextProps>;
    Fecha31884?: PrimitiveOverrideProps<TextProps>;
    Hora31885?: PrimitiveOverrideProps<TextProps>;
    Cuenta31886?: PrimitiveOverrideProps<TextProps>;
    "Dep\u00F3sito31887"?: PrimitiveOverrideProps<TextProps>;
    "Confirmaci\u00F3n31888"?: PrimitiveOverrideProps<TextProps>;
    ID31889?: PrimitiveOverrideProps<TextProps>;
    Fecha31890?: PrimitiveOverrideProps<TextProps>;
    "Compa\u00F1ia"?: PrimitiveOverrideProps<TextProps>;
    Cuenta31892?: PrimitiveOverrideProps<TextProps>;
    "Confirmaci\u00F3n31893"?: PrimitiveOverrideProps<TextProps>;
    "Dep\u00F3sito31894"?: PrimitiveOverrideProps<TextProps>;
    "Fecha Dep\u00F3sito"?: PrimitiveOverrideProps<TextProps>;
    "Ver Comprobante31896"?: PrimitiveOverrideProps<TextProps>;
    "Ver Comprobante31897"?: PrimitiveOverrideProps<TextProps>;
    "Ver Comprobante31898"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 49"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 50"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 51"?: PrimitiveOverrideProps<ViewProps>;
    Input?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131903"?: PrimitiveOverrideProps<ViewProps>;
    "Dep\u00F3sitos Pendientes31904"?: PrimitiveOverrideProps<TextProps>;
    "$9999.99 (99)"?: PrimitiveOverrideProps<TextProps>;
    "Fecha del d\u00EDa"?: PrimitiveOverrideProps<TextProps>;
    "Dep\u00F3sitos Pendientes31907"?: PrimitiveOverrideProps<TextProps>;
    "Agentes / Sucursal31908"?: PrimitiveOverrideProps<TextProps>;
    "Agentes / Sucursal31909"?: PrimitiveOverrideProps<TextProps>;
    "ACH Pendiente"?: PrimitiveOverrideProps<TextProps>;
    "Ver Todo"?: PrimitiveOverrideProps<TextProps>;
    Select31912?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131913"?: PrimitiveOverrideProps<ViewProps>;
    Fecha31914?: PrimitiveOverrideProps<TextProps>;
    Select31915?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131916"?: PrimitiveOverrideProps<ViewProps>;
    Fecha31917?: PrimitiveOverrideProps<TextProps>;
    Select31918?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131919"?: PrimitiveOverrideProps<ViewProps>;
    Fecha31920?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type DepositosProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: DepositosOverridesProps | undefined | null;
}>;
export default function Depositos(props: DepositosProps): React.ReactElement;
